M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date Fri Feb 10 23:49:35 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-10T23:49:35+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X136.0Y-88.25
X136.0Y-91.75
T2
X134.0Y-83.0
X134.0Y-97.0
X148.0Y-83.0
X148.0Y-97.0
T0
M30
